[package]
name = "validate_email"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "validate_email"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.21.1"
validator = "0.18.1"
